### ISSUE TITLE
Create a function to find data

### ISSUE THREAD

**Issue by albertocastelli** [albertocastelli/project-errore-404#1]
create 2 functions:
- find_book(), which gives the possibility to see whether a book is present in the dataset
- find_writer(), which gives the possibility to see whether a writer is present in the dataset

Also they have to show the whole row(s) containing the data

**Comment by albertocastelli** [comment]
come sei messa?

**Comment by elenalattanzio** [comment]
Both the functions have been created and the code has been updated.
