### ISSUE TITLE
Create a funciton to add books or new columns

### ISSUE THREAD

**Issue by albertocastelli** [albertocastelli/project-errore-404#2]
create 2 funcitons:
- add_col(), which gives the possibility of adding new column to the dataset. For example "copies sold", or something like this.
- add_book(), which gives the possiblity of adding new books to the dataset

**Comment by sarativ** [comment]
add_col fatto

**Comment by albertocastelli** [comment]
Quando finisci anche add_book() metto assieme

**Comment by albertocastelli** [comment]
Ho visto che hai fatto. Ho messo tutto insieme
