### ISSUE TITLE
Create a funciton to show data

### ISSUE THREAD

**Issue by albertocastelli** [albertocastelli/project-errore-404#3]
create 3 funcitons:
- show_database(), which shows the whole database
- show_genre(), which shows how many books per genre are there in the database
- show_writers(), whoch shows how many books every writer has written

**Comment by FrancescaBuoso** [comment]
Perfect! I will do this asap

**Comment by FrancescaBuoso** [comment]
Ho aggiunto show_database() e ho iniziato a scrivere il codice per i writers

**Comment by albertocastelli** [comment]
:)

**Comment by FrancescaBuoso** [comment]
Ho inserito scrittori e generi, quindi dovrei aver concluso...

**Comment by albertocastelli** [comment]
ho sistemato due cosette, ma funziona
