### ISSUE TITLE
Create a function to add data to a specific cell

### ISSUE THREAD

**Issue by albertocastelli** [albertocastelli/project-errore-404#4]
create a function add_change_value(), which is able to add (or change) data of a specific cell

**Comment by fragianca** [comment]
okay perfect

**Comment by fragianca** [comment]
finished, it should be ok

**Comment by albertocastelli** [comment]
ho cancellato la parte di verbose perché ho pensato che non era necessaria per come vogliamo strutturare le funzioni. 
Il resto invece va bene
